displayName=Nameplates & Hitsplats
author=Thource
description=Adds customizable nameplates and hitsplats to the game.
tags=nameplates,health,npc,hitsplat,damage,overhead,prayer,skull,party
version=1.1.0
plugins=dev.thource.runelite.nameplates.NameplatesPlugin
build=standard
